### ISSUE TITLE
关于vocabulary大小的疑问以及数据集处理疑问

### ISSUE THREAD

**Issue by TangJiakai** [lileipisces/POD#3]
已解决

**Comment by lileipisces** [comment]
1. T5的paper（https://arxiv.org/pdf/1910.10683.pdf）里就是这么写的（3.1.3节），不过你说的这个应该更准确。
2. 数据预处理的代码可以去P5那里看（https://github.com/jeykigung/P5/blob/main/preprocess/data_preprocess_amazon.ipynb），随机分配index确实不合理，可以看看这篇paper（https://arxiv.org/abs/2305.06569）或其他相关paper

**Comment by TangJiakai** [comment]
1. 那这个情况还是比较奇怪的，我看都用的32,100的vocab，但我也一直没找到该size对应的huggingface官方T5版本。。。大家难道就能正常运行🤔
2. P5 index方式已经被指正说是sequential index会泄漏数据信息，但是否POD仍然沿用P5的index方式，这种方式会导致指标结果的虚高以及无法泛化。

**Comment by lileipisces** [comment]
1. 影响不大，因为最后都是用同一个T5
2. sequential index确实饱受诟病，POD沿用了P5的实验设定，后续工作会进行更正

**Comment by TangJiakai** [comment]
感谢li老师耐心回复！

**Comment by TangJiakai** [comment]
@lileipisces 您好，还有个问题，我按照我自己数据的划分方式，然后用T5-base，结果出现预测的解释都一摸一样的问题，您又遇到这个问题吗？我在P5模型上是得到不错的文本生成效果的，到了POD效果就差的一塌糊涂。
以及训练在第一个epoch就已经达到eval数据集上的最佳性能。

**Comment by lileipisces** [comment]
我也遇到了这个问题，当时一直没有找到好的解决办法。猜测可能原因是训练方式的差异，P5训练的方式比较柔和（比如有用到warmup），而POD比较粗暴（learning rate比较大），导致模型过多地去拟合那些ID，失去了语言学习的能力。

**Comment by TangJiakai** [comment]
好的明白，感谢回复!
